# documentation: https://www.elastic.co/products/elasticsearch
# slogan: Elasticsearch is free and Open Source, Distributed, RESTful Search Engine.
# tags: search,engine,fulltext,full,text,elasticsearch
# category: search
# logo: svgs/elasticsearch.svg
# port: 9200

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-wolfi:8.19.0
    container_name: elasticsearch
    environment:
      - SERVICE_URL_ELASTICSEARCH_9200
      - ELASTIC_PASSWORD=${SERVICE_PASSWORD_ELASTICSEARCH}
      - ES_JAVA_OPTS=-Xms512m -Xmx512m # memory set to 512MB
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.http.ssl.enabled=false # Coolify handles SSL
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - elk
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --user elastic:${SERVICE_PASSWORD_ELASTICSEARCH} --silent --fail http://localhost:9200/_cluster/health",
        ]
      interval: 10s
      timeout: 10s
      retries: 24
  kibana:
    image: docker.elastic.co/kibana/kibana-wolfi:8.19.0
    environment:
      - SERVICE_URL_KIBANA_5601
      - ELASTIC_PASSWORD=${SERVICE_PASSWORD_ELASTICSEARCH}
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - I18N_LOCALE=en
      - I18N_STRICT_MODE=true
      - I18N_VERIFY_TRANSLATIONS=true
      - LANG=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - elk
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601"]
      interval: 30s
      timeout: 10s
      retries: 5
  logstash:
    image: docker.elastic.co/logstash/logstash-wolfi:8.19.0
    environment:
      - SERVICE_URL_LOGSTASH_9600
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTIC_PASSWORD=${SERVICE_PASSWORD_ELASTICSEARCH}
    volumes:
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9600"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - elk

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch-data:
    driver: local
